# Generated by Django 2.1.4 on 2019-01-14 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='news_article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('article', models.CharField(max_length=4000)),
                ('date', models.DateField(auto_now=True)),
                ('show_it', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Name', models.CharField(max_length=100)),
                ('product_Ref', models.CharField(max_length=200)),
                ('available_Product', models.PositiveIntegerField(null=True)),
                ('stock', models.PositiveIntegerField(null=True)),
                ('id_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.category')),
            ],
        ),
        migrations.CreateModel(
            name='profession_article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('article', models.CharField(max_length=4000)),
                ('date', models.DateField(auto_now=True)),
                ('show_it', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='project_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_Name', models.CharField(max_length=100)),
                ('promotion', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5')], default='A1', max_length=4)),
                ('duration', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='project_material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('id_Product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventaire.product')),
                ('project_Name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventaire.project_List')),
            ],
        ),
        migrations.CreateModel(
            name='project_Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_Name', models.CharField(max_length=100)),
                ('first_Name', models.CharField(max_length=100)),
                ('promotion', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5')], default='A1', max_length=4)),
                ('starting_Date', models.DateField()),
                ('return_Date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='project_reservation_material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('return_Quantity', models.PositiveIntegerField(null=True)),
                ('return_Date', models.DateField(blank=True)),
                ('id_Product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventaire.product')),
                ('id_Project_Reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventaire.project_Reservation')),
            ],
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=100)),
                ('last_Name', models.CharField(max_length=100)),
                ('promotion', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5')], default='A1', max_length=4)),
                ('starting_Date', models.DateField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('return_Quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('return_Date', models.DateField(blank=True, null=True)),
                ('id_Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventaire.product')),
            ],
        ),
        migrations.CreateModel(
            name='security_article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('article', models.CharField(max_length=4000)),
                ('date', models.DateField(auto_now=True)),
                ('show_it', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='stock_modification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=100)),
                ('last_Name', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=400)),
                ('id_Product', models.IntegerField()),
                ('name_Product', models.CharField(max_length=100)),
                ('modification', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Produit',
        ),
    ]
